name: makan_yuk
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  email_validator: ^2.1.17
  coupon_uikit: ^0.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
